name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]  # 根据您的默认分支名称调整

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # 或者您项目使用的Node版本
        
    - name: Install and Build
      run: |
        npm ci
        npm run build
    
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.5
      with:
        branch: gh-pages  # 部署到的分支
        folder: dist  # 构建输出目录
